# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e384a2a18ab4ddc03deba5ea8e023f530781e7495318e1ec4945b371e263229fb8569bc37bc8250958b050e30267b87e52ccc9f1a2bd24caeaee05e4d9e997f

test:
  secret_key_base: 61621497e785676c341d23f8902e9dcc96ead452d75a0e97cd660949484951a1db08a2b4dc2bb9ea851b4938bd44c2a2f5be9c7f04d2bf6fb600e16574945f61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
